$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    dot:false,
    autoplay:true,
    autoplayTimeout:1000,
    responsive:{
        0:{
            items:1
        },
        300:{
            item:1
        },
        500:{
            item:2
        },
        600:{
            items:3
        },
        750:{
            items:4
        },
        1000:{
            items:5
        }
    }
})